'use strict';

/**
 * Open Agent Memory Specification (OAMS)
 * routes/oams.js
 *
 * OAMS v0.1 — The open standard for agent memory interchange.
 * Import from anywhere, export to everywhere.
 *
 * Endpoints:
 *   GET  /v1/oams/spec              — Full OAMS specification JSON
 *   GET  /v1/oams/schema            — JSON Schema for validation
 *   POST /v1/oams/validate          — Validate a memory object
 *   POST /v1/oams/import/mem0       — Import memories from Mem0
 *   POST /v1/oams/import/zep        — Import memories from Zep
 *   POST /v1/oams/import/letta      — Import memories from Letta
 *   POST /v1/oams/import/json       — Import raw OAMS JSON
 *   GET  /v1/oams/export            — Export all memories as OAMS
 */

const crypto = require('crypto');

function requireAuth(req, res, apiKeys) {
  const key = (req.headers.authorization || '').replace('Bearer ', '').trim();
  if (!key || !apiKeys.get(key)) {
    res.status(401).json({ ok: false, error: { code: 'auth_required', message: 'Set Authorization: Bearer <key>' } });
    return null;
  }
  return key;
}

function hashKey(key) { return crypto.createHash('sha256').update(key).digest('hex'); }
function ok(res, data) { res.json({ ok: true, ...data }); }

// ── OAMS Specification (v0.1) ──────────────────────────────────────────────

const OAMS_SPEC = {
  oams_version: '0.1',
  released: '2026-04-02',
  author: 'slopshop.gg',
  description: 'Open Agent Memory Specification — the open standard for agent memory interchange. Import from anywhere, export to everywhere.',
  homepage: 'https://slopshop.gg/oams',
  license: 'MIT',
  mcp_compatible: true,

  memory_object: {
    description: 'A single memory unit stored in any OAMS-compatible system',
    required: ['id', 'namespace', 'key', 'value'],
    properties: {
      id:         { type: 'string', description: 'Unique identifier (UUID or slug)' },
      namespace:  { type: 'string', description: 'Logical namespace for grouping memories', default: 'default' },
      key:        { type: 'string', description: 'Human-readable key for retrieval' },
      value:      { type: 'any',    description: 'Memory content (string, object, array)' },
      tags:       { type: 'array',  items: { type: 'string' }, description: 'Tags for filtering and retrieval' },
      created:    { type: 'integer', description: 'Unix timestamp ms when memory was created' },
      updated:    { type: 'integer', description: 'Unix timestamp ms when memory was last updated' },
      ttl:        { type: 'integer', description: 'Time-to-live in seconds. 0 = never expire' },
      source:     { type: 'string', description: 'Origin of memory: notion|slack|github|cursor|manual|agent' },
      valence:    { type: 'number', description: 'Emotional valence -1.0 to 1.0 (negative=negative, positive=positive)', minimum: -1, maximum: 1 },
      version:    { type: 'integer', description: 'Version number, increments on update' },
      type:       { type: 'string', enum: ['user', 'feedback', 'project', 'reference'], description: 'Memory type for semantic filtering' },
    },
    example: {
      id: 'mem_abc123',
      namespace: 'default',
      key: 'team-error-handling-pattern',
      value: 'Services A, C, F use exponential backoff. Recommend standardizing across all services.',
      tags: ['engineering', 'patterns', 'dream-synthesis'],
      created: 1775000000000,
      updated: 1775000000001,
      ttl: 0,
      source: 'dream_engine',
      valence: 0.3,
      version: 2,
      type: 'project',
    },
  },

  dream_output: {
    description: 'Output from a completed Dream Engine session (9-stage pipeline + BiOtA)',
    required: ['dream_id', 'stages', 'insights'],
    properties: {
      dream_id:         { type: 'string', description: 'Unique dream session identifier' },
      stages:           { type: 'array',  description: 'Stages that ran in this dream cycle' },
      insights:         { type: 'array',  description: 'Synthesized insights generated by the pipeline' },
      creative_leaps:   { type: 'array',  description: 'REM Stage 7 creative recombinations' },
      predictive_leaps: { type: 'array',  description: 'Stage 9 predictive future scenarios' },
      rem_score:        { type: 'number', description: 'REM Score 0-100 (7-component composite)', minimum: 0, maximum: 100 },
      intelligence_score: { type: 'number', description: 'Intelligence Score from standard pipeline' },
      biota_iterations: { type: 'integer', description: 'BiOtA iterations completed before convergence' },
      convergence:      { type: 'number',  description: 'Schema overlap at convergence (0-1)', minimum: 0, maximum: 1 },
      duration_ms:      { type: 'integer', description: 'Total dream duration in milliseconds' },
      namespace:        { type: 'string',  description: 'Memory namespace used for this dream' },
      created_at:       { type: 'string',  description: 'ISO 8601 timestamp' },
    },
    example: {
      dream_id: 'drm_xyz789',
      stages: ['synthesize', 'pattern_extract', 'insight_generate', 'compress', 'associate', 'validate', 'evolve', 'forecast', 'reflect'],
      insights: [
        'Error handling patterns diverge across 3 service clusters',
        'Consolidating schemas could reduce cognitive load by ~40%',
      ],
      creative_leaps: [
        'What-if: Apply pattern A from auth service to payment service — projected 37% velocity gain',
        'Cross-domain synthesis: monitoring patterns + deployment patterns suggest unified observability layer',
      ],
      predictive_leaps: [
        'Anticipated: increased microservice coupling — recommend dependency audit',
      ],
      rem_score: 87,
      intelligence_score: 92.4,
      biota_iterations: 3,
      convergence: 0.92,
      duration_ms: 4200,
      namespace: 'engineering-hive',
      created_at: '2026-04-02T03:00:00.000Z',
    },
  },

  biota_metadata: {
    description: 'BiOtA (Broader Information Overlap to Abstract) session metadata — Lewis et al. 2018',
    properties: {
      iterations:          { type: 'integer', description: '3-5 iterations (mirrors human ultradian cycles)' },
      convergence_score:   { type: 'number',  description: 'Schema overlap at convergence (0-1)' },
      temperature_curve:   { type: 'array',   description: 'Per-stage temperature: [0.70, 0.65, 0.70, 0.75, 0.60, 0.65, 0.70, 1.15, 0.35, 0.40]' },
      swr_clusters:        { type: 'integer', description: 'Large SWR clusters detected in Stage 1 (Robinson Neuron 2026)' },
      go_cls_pass_rate:    { type: 'number',  description: 'Fraction of memories passing Go-CLS predictability gating' },
      shy_savings_pct:     { type: 'number',  description: 'Token savings from SHY downscaling (Stage 8)' },
      schema_history:      { type: 'array',   description: 'Per-iteration schema evolution data' },
    },
  },

  context_pack: {
    description: 'Compressed LLM context output from ContextDream mode',
    properties: {
      pack_id:         { type: 'string', description: 'Unique pack identifier' },
      gist:            { type: 'string', description: 'Compressed context preserving maximum signal density' },
      creative_leaps:  { type: 'array',  description: 'Cross-chunk creative connections from REM Stage 7' },
      predictive_slice:{ type: 'array',  description: 'Predicted relevant context for next LLM turn' },
      raw_tokens:      { type: 'integer', description: 'Original token count' },
      compressed_tokens:{ type: 'integer', description: 'Context pack token count' },
      tokens_saved:    { type: 'integer', description: 'Tokens saved via SHY + SWR pruning' },
      savings_pct:     { type: 'number',  description: 'Percentage of tokens saved (typically 55-65%)' },
    },
  },

  knowledge_graph_node: {
    description: 'A node in the DreamHive collective knowledge graph',
    properties: {
      node_id:              { type: 'string', description: 'Unique node identifier' },
      content:              { type: 'string', description: 'Node content/summary' },
      embedding_preview:    { type: 'array',  description: 'First 8 dimensions of embedding vector' },
      edges:                { type: 'array',  description: 'Connected node IDs with edge weights' },
      schema_type:          { type: 'string', description: 'Schema category: pattern|decision|insight|contradiction' },
      consolidation_stage:  { type: 'integer', description: 'Dream stage that produced this node (1-9)' },
      biota_iteration:      { type: 'integer', description: 'BiOtA iteration in which node was created' },
      hive_namespace:       { type: 'string', description: 'DreamHive namespace (team identifier)' },
    },
  },

  importers: [
    { system: 'mem0',   endpoint: 'POST /v1/oams/import/mem0',  status: 'live',    note: 'Imports memories from Mem0 API' },
    { system: 'zep',    endpoint: 'POST /v1/oams/import/zep',   status: 'live',    note: 'Imports from Zep Graphiti temporal graph' },
    { system: 'letta',  endpoint: 'POST /v1/oams/import/letta', status: 'live',    note: 'Imports from Letta stateful agent memory' },
    { system: 'json',   endpoint: 'POST /v1/oams/import/json',  status: 'live',    note: 'Import any OAMS-format JSON array' },
  ],

  changelog: [
    { version: '0.1', date: '2026-04-02', changes: ['Initial specification', 'Memory object schema', 'Dream output schema', 'BiOtA metadata schema', 'Context pack schema', 'Knowledge graph node schema', 'Importers: Mem0, Zep, Letta, JSON'] },
  ],
};

// ── JSON Schema (for validation) ─────────────────────────────────────────────

const OAMS_JSON_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://slopshop.gg/oams/schema/memory-object.json',
  title: 'OAMS Memory Object',
  type: 'object',
  required: ['id', 'namespace', 'key', 'value'],
  properties: {
    id:        { type: 'string', minLength: 1 },
    namespace: { type: 'string', minLength: 1, default: 'default' },
    key:       { type: 'string', minLength: 1 },
    value:     {},
    tags:      { type: 'array', items: { type: 'string' } },
    created:   { type: 'integer', minimum: 0 },
    updated:   { type: 'integer', minimum: 0 },
    ttl:       { type: 'integer', minimum: 0, default: 0 },
    source:    { type: 'string' },
    valence:   { type: 'number', minimum: -1, maximum: 1 },
    version:   { type: 'integer', minimum: 1 },
    type:      { type: 'string', enum: ['user', 'feedback', 'project', 'reference'] },
  },
  additionalProperties: true,
};

// ── Validation helper ─────────────────────────────────────────────────────────

function validateOAMSObject(obj) {
  const errors = [];
  if (!obj || typeof obj !== 'object') return ['Input must be an object'];
  if (!obj.id)        errors.push('Missing required field: id');
  if (!obj.namespace) errors.push('Missing required field: namespace');
  if (!obj.key)       errors.push('Missing required field: key');
  if (obj.value === undefined) errors.push('Missing required field: value');
  if (obj.valence !== undefined && (obj.valence < -1 || obj.valence > 1)) {
    errors.push('valence must be between -1 and 1');
  }
  if (obj.type !== undefined && !['user','feedback','project','reference'].includes(obj.type)) {
    errors.push('type must be one of: user, feedback, project, reference');
  }
  return errors;
}

// ── Generic import helper ─────────────────────────────────────────────────────

function importMemoriesFromOAMS(db, keyHash, memories, source) {
  let imported = 0;
  let skipped  = 0;

  for (const mem of memories) {
    try {
      const key = mem.key || mem.id || crypto.randomUUID();
      const ns  = mem.namespace || 'default';
      const val = mem.value !== undefined ? mem.value : mem.content || mem.text || mem.data || '';
      const tags = Array.isArray(mem.tags) ? mem.tags : [];
      if (!tags.includes(source)) tags.push(source, 'oams-import');

      const now = Date.now();
      db.prepare(`
        INSERT INTO memory (namespace, key, value, tags, created, updated, ttl, version, type)
        VALUES (@namespace, @key, @value, @tags, @created, @updated, @ttl, @version, @type)
        ON CONFLICT(namespace, key) DO UPDATE SET
          value   = excluded.value,
          tags    = excluded.tags,
          updated = excluded.updated,
          version = memory.version + 1
      `).run({
        namespace: ns,
        key,
        value: JSON.stringify(val),
        tags: JSON.stringify(tags),
        created: mem.created || now,
        updated: now,
        ttl: mem.ttl || 0,
        version: 1,
        type: mem.type || 'project',
      });
      imported++;
    } catch (_) {
      skipped++;
    }
  }

  return { imported, skipped, source };
}

// ─── Module export ────────────────────────────────────────────────────────────

module.exports = function (app, db, apiKeys) {

  // ── GET /v1/oams/spec (public — no auth required) ─────────────────────────
  app.get('/v1/oams/spec', (req, res) => {
    res.json({ ok: true, ...OAMS_SPEC });
  });

  // ── GET /v1/oams/schema (public) ──────────────────────────────────────────
  app.get('/v1/oams/schema', (req, res) => {
    res.json(OAMS_JSON_SCHEMA);
  });

  // ── POST /v1/oams/validate (public) ──────────────────────────────────────
  app.post('/v1/oams/validate', (req, res) => {
    const input = req.body;
    const targets = Array.isArray(input) ? input : [input];
    const results = targets.map((obj, i) => {
      const errors = validateOAMSObject(obj);
      return { index: i, valid: errors.length === 0, errors };
    });
    const allValid = results.every(r => r.valid);
    res.json({
      ok: true,
      valid: allValid,
      count: targets.length,
      results,
    });
  });

  // ── POST /v1/oams/import/mem0 ────────────────────────────────────────────
  app.post('/v1/oams/import/mem0', async (req, res) => {
    const key = requireAuth(req, res, apiKeys);
    if (!key) return;
    const keyHash = hashKey(key);

    const { memories, mem0_api_key, user_id } = req.body || {};

    // Accept pre-fetched memories array OR attempt to describe what's needed
    if (!memories || !Array.isArray(memories)) {
      return res.status(400).json({
        ok: false,
        error: {
          code: 'missing_memories',
          message: 'Provide a "memories" array in OAMS format, or export from Mem0 first',
          hint: 'From Mem0: GET https://api.mem0.ai/v1/memories/ with your Mem0 API key, then POST the result here as {"memories": [...]}'
        }
      });
    }

    // Normalize Mem0 format → OAMS
    const normalized = memories.map(m => ({
      id:        m.id || m.memory_id || crypto.randomUUID(),
      namespace: m.user_id || user_id || 'default',
      key:       m.id || m.hash || crypto.randomUUID(),
      value:     m.memory || m.text || m.content || '',
      tags:      [...(m.categories || []), 'mem0-import'],
      created:   m.created_at ? new Date(m.created_at).getTime() : Date.now(),
      updated:   m.updated_at ? new Date(m.updated_at).getTime() : Date.now(),
      source:    'mem0',
      type:      'project',
    }));

    const result = importMemoriesFromOAMS(db, keyHash, normalized, 'mem0');
    ok(res, { ...result, total_input: memories.length, oams_version: '0.1' });
  });

  // ── POST /v1/oams/import/zep ─────────────────────────────────────────────
  app.post('/v1/oams/import/zep', async (req, res) => {
    const key = requireAuth(req, res, apiKeys);
    if (!key) return;
    const keyHash = hashKey(key);

    const { memories, facts, edges } = req.body || {};
    const sources = [
      ...(memories || []),
      ...(facts || []),
      ...(edges || []),
    ];

    if (sources.length === 0) {
      return res.status(400).json({
        ok: false,
        error: {
          code: 'missing_data',
          message: 'Provide "memories", "facts", or "edges" array from Zep export',
          hint: 'From Zep: GET /api/v2/users/{userId}/memory then POST the result here'
        }
      });
    }

    const normalized = sources.map(m => ({
      id:        m.uuid || m.id || crypto.randomUUID(),
      namespace: m.session_id || 'default',
      key:       (m.content || m.text || '').slice(0, 80).replace(/\s+/g, '-').toLowerCase() || crypto.randomUUID(),
      value:     m.content || m.text || m.fact || m.name || '',
      tags:      ['zep-import', ...(m.entity_type ? [m.entity_type] : [])],
      created:   m.created_at ? new Date(m.created_at).getTime() : Date.now(),
      updated:   m.updated_at ? new Date(m.updated_at).getTime() : Date.now(),
      source:    'zep',
      type:      'project',
    }));

    const result = importMemoriesFromOAMS(db, keyHash, normalized, 'zep');
    ok(res, { ...result, total_input: sources.length, oams_version: '0.1' });
  });

  // ── POST /v1/oams/import/letta ───────────────────────────────────────────
  app.post('/v1/oams/import/letta', async (req, res) => {
    const key = requireAuth(req, res, apiKeys);
    if (!key) return;
    const keyHash = hashKey(key);

    const { blocks, passages, agent_state } = req.body || {};
    const sources = [
      ...(blocks || []),
      ...(passages || []),
      ...(agent_state ? [agent_state] : []),
    ];

    if (sources.length === 0) {
      return res.status(400).json({
        ok: false,
        error: {
          code: 'missing_data',
          message: 'Provide "blocks", "passages", or "agent_state" from Letta export',
          hint: 'From Letta: GET /v1/agents/{agent_id}/memory/blocks then POST the result here as {"blocks": [...]}'
        }
      });
    }

    const normalized = sources.map(m => ({
      id:        m.id || crypto.randomUUID(),
      namespace: m.agent_id || 'default',
      key:       m.label || m.id || crypto.randomUUID(),
      value:     m.value || m.text || m.content || '',
      tags:      ['letta-import', ...(m.label ? [m.label] : [])],
      created:   m.created_at ? new Date(m.created_at).getTime() : Date.now(),
      updated:   m.updated_at ? new Date(m.updated_at).getTime() : Date.now(),
      source:    'letta',
      type:      'project',
    }));

    const result = importMemoriesFromOAMS(db, keyHash, normalized, 'letta');
    ok(res, { ...result, total_input: sources.length, oams_version: '0.1' });
  });

  // ── POST /v1/oams/import/json ────────────────────────────────────────────
  app.post('/v1/oams/import/json', async (req, res) => {
    const key = requireAuth(req, res, apiKeys);
    if (!key) return;
    const keyHash = hashKey(key);

    const { memories } = req.body || {};
    if (!memories || !Array.isArray(memories)) {
      return res.status(400).json({
        ok: false,
        error: { code: 'missing_memories', message: 'Provide "memories" array in OAMS format' }
      });
    }

    const validationErrors = [];
    for (let i = 0; i < memories.length; i++) {
      const errs = validateOAMSObject(memories[i]);
      if (errs.length > 0) validationErrors.push({ index: i, errors: errs });
    }
    if (validationErrors.length > 0) {
      return res.status(400).json({
        ok: false,
        error: { code: 'validation_failed', message: 'Some memories failed OAMS validation', errors: validationErrors.slice(0, 10) }
      });
    }

    const result = importMemoriesFromOAMS(db, keyHash, memories, 'oams-json');
    ok(res, { ...result, total_input: memories.length, oams_version: '0.1' });
  });

  // ── GET /v1/oams/export ──────────────────────────────────────────────────
  app.get('/v1/oams/export', (req, res) => {
    const key = requireAuth(req, res, apiKeys);
    if (!key) return;
    const keyHash = hashKey(key);

    const namespace = req.query.namespace || 'default';
    const limit     = Math.min(10000, parseInt(req.query.limit) || 1000);

    let rows = [];
    try {
      rows = db.prepare(
        `SELECT namespace, key, value, tags, created, updated, ttl, version, type
         FROM memory WHERE namespace = ? LIMIT ?`
      ).all(namespace, limit);
    } catch (_) { rows = []; }

    const memories = rows.map(r => ({
      id:        crypto.randomUUID(),
      namespace: r.namespace,
      key:       r.key,
      value:     (() => { try { return JSON.parse(r.value); } catch (_) { return r.value; } })(),
      tags:      (() => { try { return JSON.parse(r.tags); } catch (_) { return []; } })(),
      created:   r.created,
      updated:   r.updated,
      ttl:       r.ttl,
      version:   r.version,
      type:      r.type,
      source:    'slopshop',
    }));

    ok(res, {
      oams_version: '0.1',
      exported_at: new Date().toISOString(),
      namespace,
      count: memories.length,
      memories,
    });
  });
};
